from yacs.config import CfgNode as CN

_C = CN()

# max number of keyframes
_C.BUFFER_SIZE = 4096

# bias patch selection towards high gradient regions?
_C.CENTROID_SEL_STRAT = 'RANDOM'

# VO config (increase for better accuracy)
_C.PATCHES_PER_FRAME = 80
_C.REMOVAL_WINDOW = 20
_C.OPTIMIZATION_WINDOW = 12
_C.PATCH_LIFETIME = 12

# threshold for keyframe removal
_C.KEYFRAME_INDEX = 4
_C.KEYFRAME_THRESH = 12.5

# camera motion model
_C.MOTION_MODEL = 'DAMPED_LINEAR'
_C.MOTION_DAMPING = 0.5

_C.MIXED_PRECISION = True

# Loop closure
_C.LOOP_CLOSURE = False
_C.BACKEND_THRESH = 64.0
_C.MAX_EDGE_AGE = 1000
_C.GLOBAL_OPT_FREQ = 15

# Classic loop closure
_C.CLASSIC_LOOP_CLOSURE = False
_C.CLASSIC_PGO_USE_THREADS = False
_C.ORB_VOCAB_PATH = "ORBvoc.txt"
_C.LOOP_CLOSE_WINDOW_SIZE = 3
_C.LOOP_RETR_THRESH = 0.04

# Distributed loop closure
_C.MULTI_ROBOT_RETRIEVAL_BACKEND = "dbow2"
_C.MULTI_ROBOT_MEGALOC_REPO = "gmberton/MegaLoc"
_C.MULTI_ROBOT_MEGALOC_MODEL_ID = "gmberton/MegaLoc"
_C.MULTI_ROBOT_MEGALOC_DEVICE = "cuda"
_C.MULTI_ROBOT_MEGALOC_DIMENSION = 8448
_C.MULTI_ROBOT_MEGALOC_THRESHOLD = 0.20
_C.MULTI_ROBOT_LOCAL_FEATURE_BACKEND = "disk"
_C.MULTI_ROBOT_XFEAT_REPO = "verlab/accelerated_features"
_C.MULTI_ROBOT_XFEAT_TOP_K = 2048
_C.MULTI_ROBOT_XFEAT_DETECTION_THRESHOLD = 0.05
_C.MULTI_ROBOT_LIGHTGLUE_MIN_CONFIDENCE = 0.10
_C.MULTI_ROBOT_BOW_REPETITIONS = 3
_C.MULTI_ROBOT_BOW_NMS = 50
_C.MULTI_ROBOT_BOW_BACKFILL = True
_C.MULTI_ROBOT_RESERVE_INFLIGHT = True
_C.MULTI_ROBOT_MAX_DEPTH = 20.0
_C.MULTI_ROBOT_MIN_INLIERS = 30
_C.MULTI_ROBOT_MIN_INLIER_RATIO = 0.20
_C.MULTI_ROBOT_TEASER_NOISE_BOUND = 0.10
_C.MULTI_ROBOT_TEASER_REQUIRED = False
_C.MULTI_ROBOT_KEYFRAME_CACHE_SIZE = 32
_C.MULTI_ROBOT_KEYFRAME_MAX_ATTEMPTS = 5
_C.MULTI_ROBOT_KEYFRAME_RETRY_DELAY = 0.5

cfg = _C
